on:
  push:
    branches: [dev]
name: 🚀 Deploy website to test.domypodklucz.pl via FTP
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v4

      - uses: actions/setup-node@v3
        with:
          node-version: "20.x"

      - uses: pnpm/action-setup@v2
        with:
          version: 9
          run_install: false

      - uses: actions/setup-node@v4
        with:
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build
        run: pnpm run build
        env:
          VITE_RECAPTCHA_SITE_KEY: ${{ secrets.VITE_RECAPTCHA_SITE_KEY }}

      - name: Replace placeholders
        run: |
          sed -i 's/%VITE_RECAPTCHA_SITE_KEY%/$VITE_RECAPTCHA_SITE_KEY/g' dist/index.html
        env:
          VITE_RECAPTCHA_SITE_KEY: ${{ secrets.VITE_RECAPTCHA_SITE_KEY }}

      - name: 📂 Sync files
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_HOST }}
          username: ${{ secrets.FTP_USER }}
          password: ${{ secrets.FTP_PASS }}
          local-dir: ./dist/
          server-dir: /public_html/test/

      - name: 📂 Sync src/php folder
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_HOST }}
          username: ${{ secrets.FTP_USER }}
          password: ${{ secrets.FTP_PASS }}
          local-dir: ./src/php/
          server-dir: /public_html/test/php/

      - name: 📂 Sync vendor folder
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        env:
          FTP_PASSIVE: "true"
        with:
          server: ${{ secrets.FTP_HOST }}
          username: ${{ secrets.FTP_USER }}
          password: ${{ secrets.FTP_PASS }}
          local-dir: ./vendor/
          server-dir: /public_html/test/vendor/
          exclude: .ftp-deploy-ignore
